# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
#  joint_model_group: todo_group_name
#  joint_model_group_pose: todo_state_name
   joint_model_group: scout_group
   joint_model_group_pose: scout_group
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
#controller_list:
#  []
controller_list:
  - name: diff_drive_comontroller
    action_ns: follow_joint_trajectory
    type: diff_drive_controller/DiffDriveController
    default: true
    joints:
      - front_left
      - front_right
      - rear_left
      - rear_right
